name: niu_server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  dart_jsonwebtoken: ^2.16.0
  either_dart: ^1.0.0
  get_it: ^8.0.3
  grpc: ^4.0.1
  hive: ^2.2.3

  path: ^1.8.0
  protobuf: ^3.1.0
  uuid: ^4.5.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.14
  mocktail: ^1.0.4
  hive_generator: ^2.0.1
